# Generated by Django 3.2 on 2023-07-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalprojet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
