# Generated by Django 3.2 on 2023-07-29 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prénom', models.CharField(max_length=30, verbose_name='Prénom ')),
                ('email', models.EmailField(max_length=30, verbose_name='Email ')),
                ('message', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, verbose_name='Email ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom ')),
                ('prénom', models.CharField(max_length=30, verbose_name='Prénom ')),
                ('cin', models.CharField(max_length=10, verbose_name='C.I.N ')),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('1', 'Homme'), ('2', 'Femme')], default='1', max_length=10)),
                ('quartier', models.CharField(choices=[('0', ' '), ('1', 'Hay Riad'), ('2', 'Hassan 2'), ('3', 'Agdal')], default='0', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Médecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom ')),
                ('prénom', models.CharField(max_length=30, verbose_name='Prénom ')),
                ('cin', models.CharField(max_length=10, verbose_name='C.I.N ')),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('spécialité', models.CharField(choices=[('spa', 'Aucune'), ('spb', 'chirurgien'), ('spc', 'Cancérologue'), ('spd', 'Gynécologue')], default='spa', max_length=20)),
                ('sexe', models.CharField(choices=[('1', 'Homme'), ('2', 'Femme')], default='1', max_length=10)),
                ('quartier', models.CharField(choices=[('0', ' '), ('1', 'Hay Riad'), ('2', 'Hassan 2'), ('3', 'Agdal')], default='0', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interprétation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interp', models.TextField(max_length=200)),
                ('date_de_création', models.DateTimeField(auto_now_add=True)),
                ('nom_médecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breastsite.médecin')),
                ('nom_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breastsite.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_img', models.CharField(choices=[('1', 'PNG'), ('2', 'JPEG'), ('3', 'JFIF')], default='1', max_length=10)),
                ('date_de_création', models.DateTimeField(auto_now_add=True)),
                ('nom_médecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breastsite.médecin')),
                ('nom_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breastsite.patient')),
            ],
        ),
    ]
