# Generated by Django 2.2 on 2021-03-08 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_consultation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prenom ')),
                ('email', models.EmailField(max_length=30, verbose_name='Email ')),
                ('password', models.CharField(max_length=30, verbose_name='password ')),
                ('message', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prenom ')),
                ('email', models.EmailField(max_length=30, verbose_name='Email ')),
                ('password', models.CharField(max_length=30, verbose_name='password ')),
                ('message', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=30, verbose_name='Nom ')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prenom ')),
                ('cin', models.CharField(max_length=10, verbose_name='C.I.N ')),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('specialite', models.CharField(choices=[('', 'Choose....'), ('Aucune', 'Aucune'), ('chirurgien', 'chirurgien'), ('Cancérologue', 'Cancérologue'), ('Gynécologue', 'Gynécologue')], default='spa', max_length=20)),
                ('sexe', models.CharField(choices=[('1', 'Homme'), ('2', 'Femme')], default='1', max_length=10)),
                ('quartier', models.CharField(choices=[('0', ' '), ('1', 'Hay Riad'), ('2', 'Hassan 2'), ('3', 'Agdal')], default='0', max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=30, verbose_name='Nom ')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prenom ')),
                ('cin', models.CharField(max_length=10, verbose_name='C.I.N ')),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('1', 'Homme'), ('2', 'Femme')], default='1', max_length=10)),
                ('quartier', models.CharField(choices=[('0', ' '), ('1', 'Hay Riad'), ('2', 'Hassan 2'), ('3', 'Agdal')], default='0', max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, verbose_name='Email ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_interpretation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.CharField(blank=True, max_length=2000)),
                ('id_consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Consultation')),
                ('id_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Image_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_img', models.CharField(max_length=1000)),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('id_consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Consultation')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Patient'),
        ),
    ]
